apiVersion: apps/v1
kind: Deployment
metadata:
  name: gjfgedv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gjfgedv
  template:
    metadata:
      labels:
        app: gjfgedv
    spec:
      containers:
      - image: okteto.dev/gjfgedv:latest
        name: gjfgedv
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "5430120e-51e8-4ba2-a954-9dea20e0af20"
        - name: Vless_Path
          value: "/vlgnghm"
        - name: Vmess_UUID
          value: "5430120e-51e8-4ba2-a954-9dea20e0af20"
        - name: Vmess_Path
          value: "/vmdtjg"
        - name: Share_Path
          value: "/v2link"
